function onCreatePost()
	makeLuaSprite('road','bgs/whippy/FG',-810,-200)
	scaleObject('road',1.1,1.1)
	makeLuaSprite('buildings','bgs/whippy/BG1',-630,-220)
	setScrollFactor('buildings',0.8,0.8)
	makeLuaSprite('buildingsfar','bgs/whippy/BG2',-150,285)
	setScrollFactor('buildingsfar',0.6,0.6)
	makeLuaSprite('picoschool','bgs/whippy/BGschool',350,170)
	setScrollFactor('picoschool',0.5,0.5)
	scaleObject('picoschool',0.8,0.8)
	makeLuaSprite('buildingswayfaaar','bgs/whippy/BG3',-300,170)
	setScrollFactor('buildingswayfaaar',0.3,0.3)
	scaleObject('buildingswayfaaar',1.1,1.1)
	makeLuaSprite('sky','bgs/whippy/SKY',-270,-250)
	setScrollFactor('sky',0.1,0.1)

	addLuaSprite('sky',0)
	addLuaSprite('buildingswayfaaar',0)
	addLuaSprite('picoschool',0)
	addLuaSprite('buildingsfar',0)
	addLuaSprite('buildings',0)
	addLuaSprite('road',0)

	setProperty('gf.alpha', 0);
end